# This file is the serverless config file to deploy on AWS.

service: aws-challenge

custom:
  devicesTableName: ${self:service}-devices-dev
  devicesTableArn:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - dynamodb
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - table/${self:custom.devicesTableName}

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  environment:
    TABLE_NAME: ${self:custom.devicesTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - ${self:custom.devicesTableArn}

package:
  individually: true
  exclude:
    - ./**

functions:
  postDevice:
    handler: bin/postDevice
    package:
      include:
        - ./bin/postDevice
    events:
      - http:
          path: api/devices
          method: POST
          cors: true
  getDevice:
    handler: bin/getDevice
    package:
      include:
        - ./bin/getDevice
    events:
      - http:
          path: api/devices/{id}
          method: GET
          cors: true

resources:
  Resources:
    DeviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.devicesTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
